name: Checkstyle

on:
  workflow_dispatch:

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Setup JDK
      uses: actions/setup-java@v3  
      with:
        distribution: 'adopt'  
        java-version: '11'

    - name: Run Checkstyle
      run: mvn checkstyle:check

